### ISSUE TITLE
clean up unecessary dependeces

### ISSUE THREAD

**Issue by vincenzopalazzo** [clightning4j/clightning4j-node#17]
@jsarenik Can you check what are the minimal dependencies needed to build the actual code with alpine

I added too much dep here https://github.com/clightning4j/clightning4j-node/blob/main/v0.11.0/Dockerfile#L30 due to the new poetry stuff.

But I realized that just pip work better, and now I need to clean up the dependeces

**Comment by jsarenik** [comment]
If I remember correctly, `alpine-sdk` package is quite bloated… reading further.

**Comment by vincenzopalazzo** [comment]
Introduce `poetry install` that is the actual procedure to install core lightning from source now, take 20 minutes longer to complete, and it is bad.

I rollback the to pip3 but I think I can minimize the dependencies in the alpine image required to compiler core lightning, so maybe you are more familiar to this.

Some of these are unnecessary
```

RUN apk update && \
    apk add ca-certificates alpine-sdk autoconf automake git libtool \
    gmp-dev sqlite-dev python3 py3-mako net-tools zlib-dev libsodium gettext su-exec \
    python3 py3-pip python3-dev libffi-dev openssl-dev postgresql postgresql-contrib postgresql-dev \
    cmake protobuf-dev
```

**Comment by jsarenik** [comment]
I have never used `poetry install` to install core lightning from source so I suppose it's not a real hard dependency for the build (my node always builds and runs latest commits on `master` branch of CLN). Yes, I noticed the `poetry` commits just now (starting with ElementsProject/lightning@74fd68521) and was a bit confused previously. Thanks for heads-up.

**Comment by vincenzopalazzo** [comment]
yeah @jsarenik you can build it because you have already all the python package, However if you build in a clean machine, you will endup in a painful process!

**Comment by jsarenik** [comment]
As far as I understand, this "painful process" is believed to be improved by adding yet another dependency…

> If you are the dealer, I'm out of the game.
> If you are the healer, it means I'm broken and lame.
>  -- Leonard Cohen, You Want It Darker (2016)

**Comment by vincenzopalazzo** [comment]
well, it is not quite right! because poetry solves a different problem that makes us stuff in the dev process, like recursion dep.

install poetry in a not well support os is painful, yes, but this solution works for us and avoids lost time-solving stupid recursion problems!

**Comment by vincenzopalazzo** [comment]
with my only comment, this issue doesn't make much sense anymore!
