### ISSUE TITLE
Improve the quality of the bash script

### ISSUE THREAD

**Issue by vincenzopalazzo** [clightning4j/clightning4j-node#3]
At the moment the bash script is very stuping, and I think it can be more smarted than now (e.f if the lightning directory exist skip it)

Maybe @jsarenik can help here, I can buy a coffee (it is nothing because I haven't a possibility but it is only to sat thanks)

bash script location https://github.com/clightning4j/clightning4j-node/blob/main/0.10.1/entrypoint.sh

**Comment by jsarenik** [comment]
See my commit, please ^^
